### ISSUE TITLE
Building on Alpine: autogen fails

### ISSUE THREAD

**Issue by niko** [thestinger/vte-ng#23] opened 2017-11-23 15:13 UTC
I'm trying to build vte-ng (and then termite) on Alpine Linux. I have to "disable-introspection" because of missing "m4 macros". When doing this autogen fails on the next step:
```
% ./autogen.sh --disable-introspection

checking whether to install the glade catalogue... no

configure: error: You must call GOBJECT_INTROSPECTION_CHECK or GOBJECT_INTROSPECTION_REQUIRE before using VAPIGEN_CHECK unless using the FOUND_INTROSPECTION argument is "yes"
```

**Comment by jelly** [comment] 2017-11-24 20:19
Or install gobject-introspection or however that is called on alpine.

**Comment by niko** [comment] 2017-11-28 10:51
Even with gobject-introspection installed I get this error when running autogen.sh:
```
configure: error: Introspection requested but M4 macros not installed. Try --disable-introspection
```

**Comment by niko** [comment] 2017-11-30 07:39
Well… _of course_ it's `gobject-introspection-dev` that's needed. Works now.

But still… `./autogen.sh --disable-introspection` doesn't work as intended, no?

**Comment by thestinger** [comment] 2017-11-30 08:35
It's not caused by any of the patches here so it's out of scope.

**Closed as completed by thestinger** 2017-11-30 08:35 UTC
